### ISSUE TITLE
Overall Navigation 

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#25]
I feel like any of these main “Tabs” should always show the same results, I think it should always default back to the index. Video: https://www.youtube.com/watch?v=Q0u5nYHBN7I

<img width="520" alt="screen shot 2017-07-17 at 3 50 03 pm" src="https://user-images.githubusercontent.com/3476109/28293179-9dfc0b18-6b07-11e7-9dfa-79d589634396.png">

**Comment by jeanpaulsio** [comment]
Fundamentally this will be a huge change because this isn't how stack navigators work by default but I don't necessarily think this is a *must* have 

I could argue that people will be confused as to why they no longer see the content they previously saw after switching tabs

**Comment by Johnsalzarulo** [comment]
I disagree. But fuck it, ship it! I'm like a 2/5 on this.

**Comment by jeanpaulsio** [comment]
closing this for now
