### ISSUE TITLE
My Bookings (Unconfirmed Booking Partial)

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#26]
Pending Tutoring Sessions in “Gray” look like something is wrong. Maybe we can just change the pending label to be a little larger and drop the “Gray” thing? 

<img width="515" alt="screen shot 2017-07-17 at 3 52 46 pm" src="https://user-images.githubusercontent.com/3476109/28293222-00c83258-6b08-11e7-9300-f4e2ef002ff2.png">

**Comment by Johnsalzarulo** [comment]
Maybe something like: 

<img width="415" alt="screen shot 2017-07-17 at 4 22 33 pm" src="https://user-images.githubusercontent.com/3476109/28294037-60605e1c-6b0c-11e7-99f4-e12d6ca1066e.png">

**Comment by jeanpaulsio** [comment]
yeah this is cool, would take a lot of logic out too which is great

**Comment by jeanpaulsio** [comment]
![img_3061](https://user-images.githubusercontent.com/8096483/28295281-71a3b87e-6b14-11e7-9d02-42cccf8e75f1.PNG)

**Comment by jeanpaulsio** [comment]
is the "today", "tomorrow" thing coming from the API and i just dont know it?

**Comment by Johnsalzarulo** [comment]
Not yet. I will give you a new 2 new endpoints on tutoring session to replace The line you have for "Date" currently saying: "Tue, Jul 18, 2017 @ 08:00am", 

The two new endpoints will be: 
**date_time_string**
**in_days **

date_time_string will return more human language like: 

- "Wednesday, Sept 23 at 8:00pm" 
- "Saturday, November 26th at 11:30am"
- "Tuesday February, 29th at 2:00pm" 

in_days will return human language like: 

- "Today" 
- "Tomorrow" 
- "In 2 Days" 
- "In 7 Days" 
- "In 2 Months" 

That way we can do something like this: 

<img width="413" alt="screen shot 2017-07-17 at 5 54 13 pm" src="https://user-images.githubusercontent.com/3476109/28295874-fa3c56ec-6b18-11e7-9b3d-654fa5e48645.png">

**Comment by Johnsalzarulo** [comment]
@jeanpaulsio - Open this back up and assign to me!

**Comment by Johnsalzarulo** [comment]
@jeanpaulsio 

This endpoint now returns the strings like I described above: 

<img width="432" alt="screen shot 2017-07-17 at 6 36 13 pm" src="https://user-images.githubusercontent.com/3476109/28296780-1ef3b682-6b1f-11e7-9f87-41c1e42f8761.png">

**Comment by jeanpaulsio** [comment]
gonna reopen till i implement this

**Comment by jeanpaulsio** [comment]
@Johnsalzarulo 

![image](https://user-images.githubusercontent.com/8096483/28305261-d4ae25ea-6b4f-11e7-9dda-f9210bdc4401.png)

I'm getting this error in postman when GET'ing from v3/tutoring_sessions

**Comment by jeanpaulsio** [comment]
sorry, ignore me, did the pg dump

**Comment by jeanpaulsio** [comment]
![img_3066](https://user-images.githubusercontent.com/8096483/28331053-9fe00978-6ba4-11e7-8b47-3132171b1422.PNG)
i put the **in_days** in the show screen, getting crowded on the index

**Comment by Johnsalzarulo** [comment]
Good thought. Pushing things into the "View" is a good call.

**Comment by Johnsalzarulo** [comment]
**🚨🚨 Nitpick 🚨🚨**
- Either "titlecase" the "JP has not confirmed this session" so it's "JP Has Not Confirmed This Session" 
- OR add a period so it's "JP has not confirmed this session."

**Comment by jeanpaulsio** [comment]
Adding a period. Javascript doesnt have a sexy way to titlecase like ruby does
