### ISSUE TITLE
Tutor Profile > Request To Book > New Booking Screen

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#28]
- [x] Change text from "Set Meeting Location" to “Set meeting Address” 
- [x] Also maybe make the touch point look more “touchable” - To many users light gray means “Disabled” . 
- [x] Also for "Choose" Subject - Same Gray issue. 
- [x] CC Field - Some kind of security Message “SSL Encrypted” with a lock would be great. People look for that shit 🙄
- [x] Remove all caps on “AFTER” - Let’s re-work this text to: 
“You won’t be charged yet. Tutoring is billed by the minute and charged when finished." ✅ Ryan approved.
<img width="618" alt="screen shot 2017-07-17 at 3 54 54 pm" src="https://user-images.githubusercontent.com/3476109/28293299-4d79cb20-6b08-11e7-9dcb-d2dc77164f6c.png">

**Comment by jeanpaulsio** [comment]
tweaked

**Comment by Johnsalzarulo** [comment]
Wow! These all look great. Also the location entry with autocomplete looks awesome.
