### ISSUE TITLE
Tutor Profile > Request To Book > New Booking Screen > Set Subject

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#29]
The Subject names have a “Backwards” arrow next to them. Feels odd. 

<img width="511" alt="screen shot 2017-07-17 at 3 57 02 pm" src="https://user-images.githubusercontent.com/3476109/28293354-97ea76d2-6b08-11e7-8932-83da1ee524ef.png">

**Comment by jeanpaulsio** [comment]
arrows pointing forward now
