### ISSUE TITLE
Tutor Profile Tweaks

### ISSUE THREAD

**Issue by Johnsalzarulo** [jeanpaulsio/whiztutor-mobile#31]
- [x] Just have reviews be “Expanded” the same way the schedule is - I’ll limit how many you get via the API on the backend. I’ll probably give you the 3 most recent. 
- [x] The review “name” feels akward bold. Maybe just have it be the same weight as the review. Or, keep bold and drop the “-” // So either do: “- John” or “**John**”
- [x] Put the “About” at the top above the education.

**Comment by jeanpaulsio** [comment]
tweaked
