### ISSUE TITLE
Auto Complete location to current location

### ISSUE THREAD

**Issue by Justinclark87** [jeanpaulsio/whiztutor-mobile#36]
Map search should find local spots

**Comment by jeanpaulsio** [comment]
Actually isn't this already doing that?

Just typing "starbucks" yields me the starbucks that are close to me:
![img_3071](https://user-images.githubusercontent.com/8096483/28342535-abce3948-6bcd-11e7-978c-4387be7b6414.PNG)

"starbucks santa cl.."
![img_3070](https://user-images.githubusercontent.com/8096483/28342553-bdb09e62-6bcd-11e7-9761-1b8fb819aea2.PNG)

@Justinclark87

**Comment by jeanpaulsio** [comment]
![image](https://user-images.githubusercontent.com/8096483/28344341-8e2a6f92-6bd7-11e7-8642-e161d12d6ac7.png)

![image](https://user-images.githubusercontent.com/8096483/28344350-98f28bf8-6bd7-11e7-8033-1462b2530702.png)


the web app has the same autocomplete - what am i missing here?

**Comment by Johnsalzarulo** [comment]
Working perfectly for me.... 

<img width="473" alt="screen shot 2017-07-18 at 5 04 35 pm" src="https://user-images.githubusercontent.com/3476109/28344854-3481bcc6-6bdb-11e7-91eb-639aa1f59963.png">
<img width="464" alt="screen shot 2017-07-18 at 5 04 25 pm" src="https://user-images.githubusercontent.com/3476109/28344855-3481f59c-6bdb-11e7-972c-1be784ac9b25.png">

**Comment by jeanpaulsio** [comment]
i'm going to take the liberty to close this issue. there's literally no other config options for me to switch over to. all the other settings would actually limit the auto complete to things like JUST business locations etc hahah
